# Site settings
title: Arogi
email: alan@arogi.com
url: https://arogi.github.io
description: "Arogi: Applied Research on Geographic Information. Geospatial Analysis for the Sharing Economy"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-gray: '#404040'
  # links: '#219ab3'
  links: '#CCFFCC'

# Footer settings
footer: Arogi, Inc.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/arogi
  - title: github
    url: https://github.com/arogi

# Build settings
markdown: kramdown
permalink: pretty
